ij-plugin:
  - changed-files:
      - any-glob-to-any-file: 'ij-plugin/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

github_actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

build:
  - changed-files:
      - any-glob-to-any-file: ['build.mill', 'mill']

Lexer:
  - changed-files:
      - any-glob-to-any-file: ['src/**/lexer/**', 'src/halotukozak/alpaca/lexer.scala']

Parser:
  - changed-files:
      - any-glob-to-any-file: ['src/**/parser/**', 'src/halotukozak/alpaca/parser.scala']

testing:
  - changed-files:
      - any-glob-to-any-file: 'test/**'
