package halotukozak
package alpaca
package internal
package lexer

import halotukozak.alpaca.ErrorHandling.Strategy
import halotukozak.regex.TokenMatcher

import scala.NamedTuple.AnyNamedTuple
import scala.annotation.publicInBinary
import scala.collection.mutable

/**
 * The result of compiling a lexer definition.
 *
 * This abstract class represents a compiled lexer that can tokenize input.
 * It is generated by the `lexer` macro and provides methods to access tokens
 * and perform tokenization.
 *
 * @tparam Ctx the global context type
 */
transparent abstract class Lexer[Ctx <: LexerCtx] @publicInBinary private[alpaca] (
  onTokenMatch: (Token[?, Ctx, ?], String, Ctx) => Ctx,
  initialCtx: () => Ctx,
)(using errorHandling: ErrorHandling[Ctx, alpaca.LexerError],
) extends Selectable:
  type Fields <: AnyNamedTuple
  type LexemeFields <: AnyNamedTuple
  final type Lexeme = lexer.Lexeme[?, ?] withFields LexemeFields
  final type LexerError = alpaca.LexerError withFields LexemeFields

  /** List of all tokens defined in this lexer, including ignored tokens. */
  @publicInBinary
  private[alpaca] def tokens: List[Token[?, Ctx, ?]]

  /**
   * Provides dynamic access to tokens by name.
   *
   * This allows accessing tokens using dot notation, e.g., `myLexer.PLUS`.
   *
   * @param fieldName the token name
   * @return the token definition
   */
  def selectDynamic(fieldName: String): Token[?, Ctx, ?]

  /**
   * Tokenizes the input character sequence.
   *
   * Processes the input from start to finish, matching tokens and building
   * a list of lexemes. Input that matches no token does not throw: it is
   * reported as a [[LexerError]], and the context's [[ErrorHandling]] decides
   * whether tokenizing stops there or skips it and goes on.
   *
   * @param input the input to tokenize
   * @return the lexemes and the final lexer context, or the errors if any input did not match; with a recovering
   *         strategy the lexemes collected despite the errors are the failure's `recovered` value
   */
  final def tokenize(input: CharSequence): Result[Ctx, List[Lexeme], LexerError] = {
    var globalCtx = initialCtx()
    globalCtx.text = input match
      case reader: LazyReader => reader
      case _ => OffsetCharSequence(input)

    val acc = mutable.ListBuffer.empty[Lexeme]
    val errors = mutable.ListBuffer.empty[LexerError]
    var stopped = false

    while !globalCtx.text.isEmpty do {
      val step: Step[Ctx] = matcher.matchAt(globalCtx.text, 0) match {
        case m if m != null && m.end > 0 =>
          val matchedStr = globalCtx.text.subSequence(0, m.end).toString
          globalCtx.lastRawMatched = matchedStr
          val found = tokensArray(m.priority)
          globalCtx.text = globalCtx.text.from(m.end)
          Step.Matched(found, matchedStr)

        case _ =>
          val cpLen = Character.charCount(Character.codePointAt(globalCtx.text, 0))
          val unexpected =
            alpaca.LexerError[LexemeFields](globalCtx.text.subSequence(0, cpLen).toString, fieldNames, globalCtx)
          errorHandling(globalCtx, unexpected.asInstanceOf[alpaca.LexerError.Of[Ctx]]) match {
            case Strategy.SkipToNextMatch =>
              val skipped = matcher.findFirst(globalCtx.text, cpLen).fold(cpLen)((firstMatching, _, _) => firstMatching)
              val matchedStr = globalCtx.text.subSequence(0, skipped).toString
              errors += alpaca.LexerError[LexemeFields](matchedStr, fieldNames, globalCtx)
              globalCtx.lastRawMatched = matchedStr
              globalCtx.text = globalCtx.text.from(skipped)
              Step.Matched(RecoveredToken(matchedStr), matchedStr)

            case Strategy.SkipOne =>
              val matchedStr = unexpected.unexpected
              errors += unexpected
              globalCtx.lastRawMatched = matchedStr
              globalCtx.text = globalCtx.text.from(cpLen)
              Step.Matched(RecoveredToken(matchedStr), matchedStr)

            case Strategy.Stop =>
              errors += unexpected
              stopped = true
              globalCtx.text = ""
              Step.Stopped
          }
      }

      step match
        case Step.Matched(token, matched) =>
          globalCtx = onTokenMatch(token, matched, globalCtx)
          if token.isInstanceOf[DefinedToken[?, Ctx, ?, ?]] then acc.addOne(globalCtx.lastLexeme.nn.asInstanceOf[Lexeme])
        case Step.Stopped =>
    }

    errors.toList match
      case Nil => Result.Success(globalCtx, acc.toList)
      case first :: rest => Result.Failure(globalCtx, Option.unless(stopped)(acc.toList), ::(first, rest))
  }

  /** Compiled token-matcher; built at macro time. */
  protected def matcher: TokenMatcher

  private lazy val tokensArray: Vector[Token[?, Ctx, ?]] = tokens.toVector

  private val fieldNames: Array[String] = initialCtx().productElementNames.toArray

/** The outcome of one step of [[Lexer.tokenize]]: a token matched (or recovered) from `text`, or a stop. */
private enum Step[-Ctx <: LexerCtx]:
  case Matched(token: Token[?, Ctx, ?], text: String)
  case Stopped

extension (input: CharSequence)
  private[alpaca] def from(pos: Int): CharSequence = input match
    case ocs: OffsetCharSequence => ocs.from(pos)
    case lfr: LazyReader => lfr.from(pos)
    case _ => input.subSequence(pos, input.length)
